version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5001:5000"
    depends_on:
      - prometheus
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mynetwork

networks:
  mynetwork:

  
